# Generated by Django 4.1.3 on 2023-04-04 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('img_id', models.AutoField(primary_key=True, serialize=False)),
                ('img_file', models.ImageField(upload_to='uploads/%Y/%m/%d/')),
                ('img_name', models.CharField(max_length=255)),
            ],
        ),
    ]
