# Generated by Django 4.1.3 on 2023-04-04 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('picbed', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='img_name',
        ),
    ]
