# Generated by Django 4.1.3 on 2023-04-16 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picbed', '0003_alter_image_img_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='filename',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='img_file',
            field=models.ImageField(upload_to='data/picbed/uploads/%Y/%m/%d/'),
        ),
    ]
