# Generated by Django 4.1.3 on 2023-04-16 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0008_current_tag_user_is_check_accepted'),
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnsList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ans_list', models.ManyToManyField(default=[], to='review.ansdata')),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='task.task')),
            ],
        ),
        migrations.DeleteModel(
            name='AnsListData',
        ),
    ]
