# Generated by Django 4.1.3 on 2023-05-18 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0014_user_face_base64_alter_user_invite_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertise',
            fields=[
                ('ad_id', models.AutoField(primary_key=True, serialize=False)),
                ('ad_pub_time', models.FloatField(default=0)),
                ('ad_time', models.FloatField(default=0)),
                ('ad_type', models.CharField(max_length=255)),
                ('img_url', models.CharField(max_length=255)),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
