# Generated by Django 4.1.3 on 2023-04-03 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Current_tag_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted_at', models.IntegerField()),
                ('tag_user', models.ManyToManyField(to='user.user')),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_id', models.IntegerField()),
                ('tag_user', models.ManyToManyField(to='user.user')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=255)),
                ('data_type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_type', models.CharField(max_length=20)),
                ('task_style', models.CharField(max_length=200)),
                ('reward_per_q', models.IntegerField(default=0)),
                ('time_limit_per_q', models.IntegerField(default=0)),
                ('total_time_limit', models.IntegerField(default=0)),
                ('auto_ac', models.BooleanField(default=True)),
                ('manual_ac', models.BooleanField(default=False)),
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('distribute_user_num', models.IntegerField(default=0)),
                ('q_num', models.IntegerField(default=0)),
                ('task_name', models.CharField(default='task', max_length=24)),
                ('result_type', models.CharField(max_length=255)),
                ('current_tag_user_list', models.ManyToManyField(to='task.current_tag_user')),
                ('past_tag_user_list', models.ManyToManyField(to='user.user')),
                ('progress', models.ManyToManyField(to='task.progress')),
                ('publisher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='published_task', to='user.user')),
                ('questions', models.ManyToManyField(to='task.question')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_res', models.CharField(max_length=255)),
                ('tag_user', models.ManyToManyField(to='user.user')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='result',
            field=models.ManyToManyField(to='task.result'),
        ),
    ]
