# Generated by Django 4.1.3 on 2023-04-05 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextData',
            fields=[
                ('data', models.TextField(max_length=2000)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Data',
        ),
        migrations.RemoveField(
            model_name='task',
            name='auto_ac',
        ),
        migrations.RemoveField(
            model_name='task',
            name='manual_ac',
        ),
        migrations.AddField(
            model_name='task',
            name='accept_method',
            field=models.CharField(default='manual', max_length=255),
        ),
        migrations.RemoveField(
            model_name='result',
            name='tag_user',
        ),
        migrations.AlterField(
            model_name='task',
            name='task_style',
            field=models.CharField(max_length=255),
        ),
        migrations.AddField(
            model_name='result',
            name='tag_user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
    ]
