# Generated by Django 4.1.3 on 2023-04-06 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_textdata_delete_data_remove_task_auto_ac_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='q_id',
            field=models.BigIntegerField(default=1),
        ),
    ]
