# Generated by Django 4.1.3 on 2023-04-12 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_tagtype_question_tag_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='tag_type',
            field=models.ManyToManyField(default=[], to='task.tagtype'),
        ),
    ]
