# Generated by Django 4.1.3 on 2023-04-16 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_current_tag_user_is_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='current_tag_user',
            name='is_check_accepted',
            field=models.CharField(default='none', max_length=255),
        ),
    ]
