# Generated by Django 4.1.3 on 2023-04-16 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_remove_anslist_task'),
        ('task', '0008_current_tag_user_is_check_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='ans_list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='review.anslist'),
        ),
    ]
