# Generated by Django 4.1.3 on 2023-04-23 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0011_alter_task_check_result'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='task',
            name='task_style',
        ),
        migrations.AddField(
            model_name='task',
            name='task_style',
            field=models.ManyToManyField(default=[], to='task.category'),
        ),
    ]
