# Generated by Django 4.1.3 on 2023-04-24 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0012_remove_task_categories_remove_task_task_style_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='strategy',
            field=models.CharField(default='order', max_length=255),
        ),
    ]
