# Generated by Django 4.1.3 on 2023-05-09 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_category_category'),
        ('task', '0012_remove_task_categories_task_strategy_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InputType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_tip', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameModel(
            old_name='Current_tag_user',
            new_name='CurrentTagUser',
        ),
        migrations.AddField(
            model_name='task',
            name='input_type',
            field=models.ManyToManyField(default=[], to='task.inputtype'),
        ),
    ]
