# Generated by Django 4.1.3 on 2023-04-24 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_category_usercategory_delete_banuser_user_categories'),
        ('task', '0013_task_strategy'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AlterField(
            model_name='task',
            name='task_style',
            field=models.ManyToManyField(default=[], to='user.category'),
        ),
    ]
