# Generated by Django 4.1.3 on 2023-05-09 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0013_inputtype_rename_current_tag_user_currenttaguser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='cut_num',
            field=models.IntegerField(default=None),
        ),
    ]
