# Generated by Django 4.1.3 on 2023-05-09 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0014_task_cut_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='cut_num',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='question',
            name='input_type',
            field=models.ManyToManyField(default=[], to='task.inputtype'),
        ),
        migrations.CreateModel(
            name='InputResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_res', models.CharField(max_length=255)),
                ('input_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.inputtype')),
            ],
        ),
        migrations.AddField(
            model_name='result',
            name='input_result',
            field=models.ManyToManyField(default=[], to='task.inputresult'),
        ),
    ]
