# Generated by Django 4.1.3 on 2023-05-09 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0015_question_cut_num_question_input_type_inputresult_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='cut_num',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
