# Generated by Django 4.1.3 on 2023-05-09 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0016_alter_task_cut_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='cut_num',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
