# Generated by Django 4.1.3 on 2023-05-09 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_category_category'),
        ('task', '0017_alter_question_cut_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='publisher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='published_task', to='user.user'),
            preserve_default=False,
        ),
    ]
