# Generated by Django 4.1.3 on 2023-05-14 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0021_result_finish_time_result_start_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currenttaguser',
            name='is_check_accepted',
        ),
        migrations.RemoveField(
            model_name='currenttaguser',
            name='is_finished',
        ),
        migrations.AddField(
            model_name='currenttaguser',
            name='state',
            field=models.CharField(default='not_handle', max_length=255),
        ),
    ]
