# Generated by Django 4.1.3 on 2023-05-14 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0022_remove_currenttaguser_is_check_accepted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportinfo',
            name='reason',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
