# Generated by Django 4.1.3 on 2023-05-14 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_user_face_base64_alter_user_invite_code_and_more'),
        ('task', '0023_reportinfo_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportinfo',
            name='user',
        ),
        migrations.AddField(
            model_name='reportinfo',
            name='report_req',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='report_info_report_req', to='user.user'),
        ),
        migrations.AddField(
            model_name='reportinfo',
            name='reportee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='report_info_reportee', to='user.user'),
        ),
    ]
