# Generated by Django 4.1.3 on 2023-04-08 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_balance',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='credit_score',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='score',
            field=models.IntegerField(default=100),
        ),
        migrations.CreateModel(
            name='BanUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release_time', models.FloatField(default=0)),
                ('ban_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
