# Generated by Django 4.1.3 on 2023-05-10 09:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0005_alter_category_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='email_valid',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='email_valid_expire',
            field=models.DateTimeField(
                default=datetime.datetime(1970, 1, 1, 0, 0).replace(tzinfo=datetime.timezone.utc)),
        ),
    ]
