# Generated by Django 4.1.3 on 2023-05-10 10:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_user_email_user_email_valid_user_email_valid_expire'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerify',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('email_valid', models.CharField(max_length=255, null=True)),
                ('email_valid_expire', models.DateTimeField(default=datetime.datetime(1970, 1, 1, 8, 0))),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='email_valid',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email_valid_expire',
        ),
    ]
