# Generated by Django 4.1.3 on 2023-05-10 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tag_score',
            field=models.IntegerField(default=0),
        ),
    ]
