# Generated by Django 4.1.3 on 2023-05-10 18:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_user_bank_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverify',
            name='email_valid_expire',
            field=models.DateTimeField(default=datetime.datetime(1970, 1, 1, 8, 0, tzinfo=datetime.timezone.utc)),
        ),
    ]
