# Generated by Django 4.1.3 on 2023-05-13 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_alter_emailverify_email_valid_expire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='account_balance',
        ),
    ]
