# Generated by Django 4.1.3 on 2023-05-13 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_remove_user_account_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='face_base64',
            field=models.TextField(max_length=1000000, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='invite_code',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(max_length=255),
        ),
    ]
